#!/usr/bin/env ruby

# problem 1.

# Multiple of 3 and 5
# Find the sum of all the multiples of 3 or 5 below 1000.

def p1(n)
  ret = 0
  (1..n).each do |n|
    if (n % 3 == 0) or (n % 5==0)
      ret += n
    end
  end
  ret
end

p1(100)

# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the
# even-valued terms.
