; Problem 45.
; Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

; Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
; Pentagonal   Pn=n(3n−1)/2   1, 5, 12, 22, 35, ...
; Hexagonal   Hn=n(2n−1)   1, 6, 15, 28, 45, ...
; It can be verified that T285 = P165 = H143 = 40755.

; Find the next triangle number that is also pentagonal and hexagonal.

(define tri
  (lambda (n)
    (/ (* n (+ n 1)) 2)))

(define penta
  (lambda (n)
    (/ (* n (- (* 3 n) 1)) 2)))

(define hexa
  (lambda (n)
    (* n (- (* 2 n) 1))))

;(= (tri 285) (penta 165) (hexa 143))
;true

;;村上の回答見てバージョンアップ。
;;そうか、tri number は hexa number だったか。
(define ph
  (lambda (p h)
    (cond
      ((= (penta p) (hexa h)) (list p h))
      ((< (penta p) (hexa h)) (ph (+ 1 p) h))
      ((> (penta p) (hexa h)) (ph p (+ 1 h))))))

; (time (ph 165 (+ 143 1)))
; cpu time: 5 real time: 5 gc time: 0
; '(31977 27693)

;; 同じように書いた clojure だと
; (time (ph' 165 144))
; "Elapsed time: 59.005417 msecs"
; [31977 27693]
;; 10倍？ruby でも書いてみるか。

