(ns hkim0331.p12)
; The sequence of triangle numbers is generated by adding the natural numbers.
; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
; The first ten terms would be:
;
; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;
; Let us list the factors of the first seven triangle numbers:
;
;  1: 1
;  3: 1,3
;  6: 1,2,3,6
; 10: 1,2,5,10
; 15: 1,3,5,15
; 21: 1,3,7,21
; 28: 1,2,4,7,14,28
; We can see that 28 is the first triangle number to have over five divisors.
;
; What is the value of the first triangle number to have over five hundred divisors?

(defn tn [[index num]]
  (let [next (+ 1 index)]
    [next (+ next num)]))

(def triangle-number
  (iterate tn [1 1]))

(take 10 triangle-number)

(defn- aux [n m ret]
  (cond
    (< n (* m m)) ret
    (zero? (rem n m)) (aux n (+ 1 m) (into ret [m (/ n m)]))
    :else (aux n (+ 1 m) ret)))

(defn divisors [n]
  (aux n 2 [1 n]))

(divisors 28)

(defn p12 [n]
  (first
    (drop-while #(< (count (divisors (second %))) n)
                triangle-number)))

(p12 6)
;[7,28]
(p12 500)

